# Generated by Django 5.1 on 2024-08-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0002_app_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='is_adult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='app',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='app',
            name='is_newly_added',
            field=models.BooleanField(default=False),
        ),
    ]
