# Generated by Django 5.1 on 2024-08-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0003_app_is_adult_app_is_featured_app_is_newly_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='is_adult',
        ),
        migrations.RemoveField(
            model_name='app',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='app',
            name='is_newly_added',
        ),
        migrations.AddField(
            model_name='app',
            name='sub_category',
            field=models.CharField(choices=[('featured', 'Featured'), ('newly_added', 'Newly Added'), ('adult', 'Adult'), ('kids', 'Kids'), ('sports', 'Sports'), ('ott', 'Ott'), ('social', 'Social'), ('education', 'Education'), ('productive', 'Productive')], default='featured', max_length=50),
        ),
    ]
