# Generated by Django 5.1 on 2024-08-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0004_remove_app_is_adult_remove_app_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='sub_category',
            field=models.CharField(choices=[('featured', 'Featured'), ('newly_added', 'Newly Added'), ('adult', 'Adult'), ('kids', 'Kids'), ('sports', 'Sports'), ('ott', 'Ott'), ('social', 'Social'), ('education', 'Education'), ('productive', 'Productive')], default='newly_added', max_length=50),
        ),
    ]
