# Generated by Django 5.1 on 2024-08-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0005_alter_app_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='sub_category',
            field=models.CharField(choices=[('featured', 'Featured'), ('newly_added', 'Newly Added'), ('adult', 'Adult'), ('entertainment', 'Entertainment'), ('social', 'Social'), ('productive', 'Productive'), ('communication', 'Communication'), ('premium', 'Premium Apps'), ('tools_and_utilities ', 'Tools & utilities '), ('editor_choice_apps', "Editor's choice Apps"), ('editing_apps', 'Editing Apps')], default='newly_added', max_length=50),
        ),
    ]
