# Generated by Django 5.1 on 2024-08-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0006_alter_app_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='download_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='rating_no',
            field=models.IntegerField(default=0),
        ),
    ]
