# Generated by Django 5.1 on 2024-08-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0007_app_download_link_app_rating_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='download_no',
            field=models.IntegerField(default=0),
        ),
    ]
